name: "Crowdsec Firewall Bouncer"
description: "Crowdsec bouncer written in golang for firewalls"
url: "https://github.com/crowdsecurity/home-assistant-addons/tree/main/crowdsec-firewall-bouncer/DOCS.md"
version: "v0.0.34"
slug: crowdsec-firewall-bouncer
init: false
host_network: true
privileged:
  - NET_ADMIN
arch:
  - amd64
  - armhf
  - aarch64
  - armv7
  - i386
image: "ghcr.io/jtdoepke/{arch}-addon-crowdsec-firewall-bouncer"
options:
  api_url: "http://424ccef4-crowdsec:8080/"
  api_key: ""
  tls_enabled: false
  tls_ca_cert: ""
  tls_client_cert: ""
  tls_client_key: ""
  tls_skip_verify: false
  update_frequency: "10s"
  log_level: info
  nftables_hooks:
    - input
schema:
  api_url: str
  api_key: str?
  tls_enabled: bool?
  tls_ca_cert: str?
  tls_client_cert: str?
  tls_client_key: str?
  tls_skip_verify: bool?
  update_frequency: str
  nftables_hooks:
    - "match(^(prerouting|input|forward|output|postrouting|ingress)$)"
  log_level: list(info|error|debug)
map:
  - config:rw
  - ssl:ro
