name: "Crowdsec"
description: "CrowdSec - the open-source and participative IPS"
url: "https://github.com/crowdsecurity/home-assistant-addons/blob/main/crowdsec/DOCS.md"
version: "1.7.4"
slug: "crowdsec"
init: false
ingress: true
ingress_port: 7681
ingress_stream: true
arch:
  - amd64
  - armhf
  - aarch64
  - armv7
  - i386
ports:
  8080/tcp: null
ports_description:
  8080/tcp: "CrowdSec Local API"
image: "ghcr.io/jtdoepke/{arch}-addon-crowdsec"
options:
  acquisition: |
    ---
    source: journalctl
    journalctl_filter:
      - "--directory=/var/log/journal/"
    labels:
      type: syslog
  disable_lapi: false
  remote_lapi_url: ""
  agent_username: ""
  agent_password: ""
  tls_enabled: false
  tls_ca_cert: ""
  tls_client_cert: ""
  tls_client_key: ""
  tls_skip_verify: false
  collections:
    - crowdsecurity/home-assistant
  parsers: []
  scenarios: []
  postoverflows: []
  parsers_to_disable: []
  scenarios_to_disable: []
  disable_online_api: false
environment:
  CONFIG_FILE: "/config/.storage/crowdsec/config/config.yaml"
schema:
  acquisition: str
  disable_lapi: bool
  remote_lapi_url: str
  agent_username: str?
  agent_password: str?
  tls_enabled: bool?
  tls_ca_cert: str?
  tls_client_cert: str?
  tls_client_key: str?
  tls_skip_verify: bool?
  collections:
    - str
  parsers:
    - str
  scenarios:
    - str
  postoverflows:
    - str
  parsers_to_disable:
    - str
  scenarios_to_disable:
    - str
  disable_online_api: bool
map:
  - config:rw
  - ssl:ro
panel_icon: mdi:console-network
panel_title: Crowdsec Terminal
journald: true
